### ISSUE TITLE
BUG: Weapon System in Main Scene throws errors

### ISSUE THREAD

**Issue by JosephCoppola** [SpaceSpaceSpace/Space#28]
The UI seems to be broken a bit. We will need to look at this with @Nolnocn and @Honeybunch

**Comment by Honeybunch** [comment]
What's broken about it? Other than the attachment points being miscolored I don't see anything super out of place.

**Comment by Honeybunch** [comment]
Fixed in a0fc638 I think.

**Comment by JosephCoppola** [comment]
Confirmed
